#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebAPI.LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OdeonAir")]
	public partial class dbLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHotel(Hotel instance);
    partial void UpdateHotel(Hotel instance);
    partial void DeleteHotel(Hotel instance);
    #endregion
		
		public dbLINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CESTURConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hotel> Hotel
		{
			get
			{
				return this.GetTable<Hotel>();
			}
		}
		
		public System.Data.Linq.Table<_RACKVIEW> _RACKVIEW
		{
			get
			{
				return this.GetTable<_RACKVIEW>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hotel")]
	public partial class Hotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IsMainSourceHotel;
		
		private string _Name;
		
		private string _Description;
		
		private string _ShortDesc;
		
		private string _HotelType;
		
		private System.Nullable<int> _RoomNumber;
		
		private int _Active;
		
		private System.Nullable<System.DateTime> _ActivationDate;
		
		private string _RoomNumberDesc;
		
		private string _Address;
		
		private string _Bolge;
		
		private string _City;
		
		private string _Ilce;
		
		private string _Mevki;
		
		private string _Country;
		
		private System.Nullable<int> _AddressSame;
		
		private string _AddressInvoice;
		
		private string _AddressInvoiceCity;
		
		private string _AddressInvoiceCountry;
		
		private string _CommercialName;
		
		private string _Region;
		
		private string _Zip;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _Fax;
		
		private string _Airport;
		
		private System.Nullable<int> _AirportDistance;
		
		private string _Email;
		
		private string _Email2;
		
		private string _Web;
		
		private string _Owner;
		
		private string _Gm;
		
		private string _TaxOffice;
		
		private string _TaxId;
		
		private string _DefaultBoard;
		
		private string _AccessKey;
		
		private int _Inactive;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private System.Nullable<int> _CityDistance;
		
		private string _VPosTerminalID;
		
		private string _VPosMerchantID;
		
		private string _VPosProvUserID;
		
		private string _VPosUserID;
		
		private string _VPosProvisionPassword;
		
		private string _VPosCompanyName;
		
		private string _Background;
		
		private string _Foreground;
		
		private string _Foreground2;
		
		private string _Background2;
		
		private string _Lat;
		
		private string _Lng;
		
		private System.Nullable<int> _IsWinter;
		
		private System.Nullable<int> _HomePage;
		
		private string _BookingComId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsMainSourceHotelChanging(int value);
    partial void OnIsMainSourceHotelChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnShortDescChanging(string value);
    partial void OnShortDescChanged();
    partial void OnHotelTypeChanging(string value);
    partial void OnHotelTypeChanged();
    partial void OnRoomNumberChanging(System.Nullable<int> value);
    partial void OnRoomNumberChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    partial void OnActivationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActivationDateChanged();
    partial void OnRoomNumberDescChanging(string value);
    partial void OnRoomNumberDescChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnBolgeChanging(string value);
    partial void OnBolgeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnMevkiChanging(string value);
    partial void OnMevkiChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnAddressSameChanging(System.Nullable<int> value);
    partial void OnAddressSameChanged();
    partial void OnAddressInvoiceChanging(string value);
    partial void OnAddressInvoiceChanged();
    partial void OnAddressInvoiceCityChanging(string value);
    partial void OnAddressInvoiceCityChanged();
    partial void OnAddressInvoiceCountryChanging(string value);
    partial void OnAddressInvoiceCountryChanged();
    partial void OnCommercialNameChanging(string value);
    partial void OnCommercialNameChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnPhone1Changing(string value);
    partial void OnPhone1Changed();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnPhone3Changing(string value);
    partial void OnPhone3Changed();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnAirportChanging(string value);
    partial void OnAirportChanged();
    partial void OnAirportDistanceChanging(System.Nullable<int> value);
    partial void OnAirportDistanceChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmail2Changing(string value);
    partial void OnEmail2Changed();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    partial void OnOwnerChanging(string value);
    partial void OnOwnerChanged();
    partial void OnGmChanging(string value);
    partial void OnGmChanged();
    partial void OnTaxOfficeChanging(string value);
    partial void OnTaxOfficeChanged();
    partial void OnTaxIdChanging(string value);
    partial void OnTaxIdChanged();
    partial void OnDefaultBoardChanging(string value);
    partial void OnDefaultBoardChanged();
    partial void OnAccessKeyChanging(string value);
    partial void OnAccessKeyChanged();
    partial void OnInactiveChanging(int value);
    partial void OnInactiveChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCityDistanceChanging(System.Nullable<int> value);
    partial void OnCityDistanceChanged();
    partial void OnVPosTerminalIDChanging(string value);
    partial void OnVPosTerminalIDChanged();
    partial void OnVPosMerchantIDChanging(string value);
    partial void OnVPosMerchantIDChanged();
    partial void OnVPosProvUserIDChanging(string value);
    partial void OnVPosProvUserIDChanged();
    partial void OnVPosUserIDChanging(string value);
    partial void OnVPosUserIDChanged();
    partial void OnVPosProvisionPasswordChanging(string value);
    partial void OnVPosProvisionPasswordChanged();
    partial void OnVPosCompanyNameChanging(string value);
    partial void OnVPosCompanyNameChanged();
    partial void OnBackgroundChanging(string value);
    partial void OnBackgroundChanged();
    partial void OnForegroundChanging(string value);
    partial void OnForegroundChanged();
    partial void OnForeground2Changing(string value);
    partial void OnForeground2Changed();
    partial void OnBackground2Changing(string value);
    partial void OnBackground2Changed();
    partial void OnLatChanging(string value);
    partial void OnLatChanged();
    partial void OnLngChanging(string value);
    partial void OnLngChanged();
    partial void OnIsWinterChanging(System.Nullable<int> value);
    partial void OnIsWinterChanged();
    partial void OnHomePageChanging(System.Nullable<int> value);
    partial void OnHomePageChanged();
    partial void OnBookingComIdChanging(string value);
    partial void OnBookingComIdChanged();
    #endregion
		
		public Hotel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMainSourceHotel", DbType="Int NOT NULL")]
		public int IsMainSourceHotel
		{
			get
			{
				return this._IsMainSourceHotel;
			}
			set
			{
				if ((this._IsMainSourceHotel != value))
				{
					this.OnIsMainSourceHotelChanging(value);
					this.SendPropertyChanging();
					this._IsMainSourceHotel = value;
					this.SendPropertyChanged("IsMainSourceHotel");
					this.OnIsMainSourceHotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this.OnShortDescChanging(value);
					this.SendPropertyChanging();
					this._ShortDesc = value;
					this.SendPropertyChanged("ShortDesc");
					this.OnShortDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelType", DbType="NVarChar(10)")]
		public string HotelType
		{
			get
			{
				return this._HotelType;
			}
			set
			{
				if ((this._HotelType != value))
				{
					this.OnHotelTypeChanging(value);
					this.SendPropertyChanging();
					this._HotelType = value;
					this.SendPropertyChanged("HotelType");
					this.OnHotelTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNumber", DbType="Int")]
		public System.Nullable<int> RoomNumber
		{
			get
			{
				return this._RoomNumber;
			}
			set
			{
				if ((this._RoomNumber != value))
				{
					this.OnRoomNumberChanging(value);
					this.SendPropertyChanging();
					this._RoomNumber = value;
					this.SendPropertyChanged("RoomNumber");
					this.OnRoomNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActivationDate
		{
			get
			{
				return this._ActivationDate;
			}
			set
			{
				if ((this._ActivationDate != value))
				{
					this.OnActivationDateChanging(value);
					this.SendPropertyChanging();
					this._ActivationDate = value;
					this.SendPropertyChanged("ActivationDate");
					this.OnActivationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNumberDesc", DbType="NVarChar(250)")]
		public string RoomNumberDesc
		{
			get
			{
				return this._RoomNumberDesc;
			}
			set
			{
				if ((this._RoomNumberDesc != value))
				{
					this.OnRoomNumberDescChanging(value);
					this.SendPropertyChanging();
					this._RoomNumberDesc = value;
					this.SendPropertyChanged("RoomNumberDesc");
					this.OnRoomNumberDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(1024)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolge", DbType="NVarChar(128)")]
		public string Bolge
		{
			get
			{
				return this._Bolge;
			}
			set
			{
				if ((this._Bolge != value))
				{
					this.OnBolgeChanging(value);
					this.SendPropertyChanging();
					this._Bolge = value;
					this.SendPropertyChanged("Bolge");
					this.OnBolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(128)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(128)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mevki", DbType="NVarChar(128)")]
		public string Mevki
		{
			get
			{
				return this._Mevki;
			}
			set
			{
				if ((this._Mevki != value))
				{
					this.OnMevkiChanging(value);
					this.SendPropertyChanging();
					this._Mevki = value;
					this.SendPropertyChanged("Mevki");
					this.OnMevkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(64)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressSame", DbType="Int")]
		public System.Nullable<int> AddressSame
		{
			get
			{
				return this._AddressSame;
			}
			set
			{
				if ((this._AddressSame != value))
				{
					this.OnAddressSameChanging(value);
					this.SendPropertyChanging();
					this._AddressSame = value;
					this.SendPropertyChanged("AddressSame");
					this.OnAddressSameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressInvoice", DbType="NVarChar(1024)")]
		public string AddressInvoice
		{
			get
			{
				return this._AddressInvoice;
			}
			set
			{
				if ((this._AddressInvoice != value))
				{
					this.OnAddressInvoiceChanging(value);
					this.SendPropertyChanging();
					this._AddressInvoice = value;
					this.SendPropertyChanged("AddressInvoice");
					this.OnAddressInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressInvoiceCity", DbType="NVarChar(128)")]
		public string AddressInvoiceCity
		{
			get
			{
				return this._AddressInvoiceCity;
			}
			set
			{
				if ((this._AddressInvoiceCity != value))
				{
					this.OnAddressInvoiceCityChanging(value);
					this.SendPropertyChanging();
					this._AddressInvoiceCity = value;
					this.SendPropertyChanged("AddressInvoiceCity");
					this.OnAddressInvoiceCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressInvoiceCountry", DbType="NVarChar(64)")]
		public string AddressInvoiceCountry
		{
			get
			{
				return this._AddressInvoiceCountry;
			}
			set
			{
				if ((this._AddressInvoiceCountry != value))
				{
					this.OnAddressInvoiceCountryChanging(value);
					this.SendPropertyChanging();
					this._AddressInvoiceCountry = value;
					this.SendPropertyChanged("AddressInvoiceCountry");
					this.OnAddressInvoiceCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommercialName", DbType="VarChar(1024)")]
		public string CommercialName
		{
			get
			{
				return this._CommercialName;
			}
			set
			{
				if ((this._CommercialName != value))
				{
					this.OnCommercialNameChanging(value);
					this.SendPropertyChanging();
					this._CommercialName = value;
					this.SendPropertyChanged("CommercialName");
					this.OnCommercialNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="VarChar(64)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(60)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="NVarChar(25)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this.OnPhone1Changing(value);
					this.SendPropertyChanging();
					this._Phone1 = value;
					this.SendPropertyChanged("Phone1");
					this.OnPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="NVarChar(25)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="NVarChar(25)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this.OnPhone3Changing(value);
					this.SendPropertyChanging();
					this._Phone3 = value;
					this.SendPropertyChanged("Phone3");
					this.OnPhone3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airport", DbType="NVarChar(255)")]
		public string Airport
		{
			get
			{
				return this._Airport;
			}
			set
			{
				if ((this._Airport != value))
				{
					this.OnAirportChanging(value);
					this.SendPropertyChanging();
					this._Airport = value;
					this.SendPropertyChanged("Airport");
					this.OnAirportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirportDistance", DbType="Int")]
		public System.Nullable<int> AirportDistance
		{
			get
			{
				return this._AirportDistance;
			}
			set
			{
				if ((this._AirportDistance != value))
				{
					this.OnAirportDistanceChanging(value);
					this.SendPropertyChanging();
					this._AirportDistance = value;
					this.SendPropertyChanged("AirportDistance");
					this.OnAirportDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(511)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email2", DbType="NVarChar(511)")]
		public string Email2
		{
			get
			{
				return this._Email2;
			}
			set
			{
				if ((this._Email2 != value))
				{
					this.OnEmail2Changing(value);
					this.SendPropertyChanging();
					this._Email2 = value;
					this.SendPropertyChanged("Email2");
					this.OnEmail2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(511)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="NVarChar(1024)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gm", DbType="NVarChar(255)")]
		public string Gm
		{
			get
			{
				return this._Gm;
			}
			set
			{
				if ((this._Gm != value))
				{
					this.OnGmChanging(value);
					this.SendPropertyChanging();
					this._Gm = value;
					this.SendPropertyChanged("Gm");
					this.OnGmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxOffice", DbType="NVarChar(255)")]
		public string TaxOffice
		{
			get
			{
				return this._TaxOffice;
			}
			set
			{
				if ((this._TaxOffice != value))
				{
					this.OnTaxOfficeChanging(value);
					this.SendPropertyChanging();
					this._TaxOffice = value;
					this.SendPropertyChanged("TaxOffice");
					this.OnTaxOfficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxId", DbType="VarChar(255)")]
		public string TaxId
		{
			get
			{
				return this._TaxId;
			}
			set
			{
				if ((this._TaxId != value))
				{
					this.OnTaxIdChanging(value);
					this.SendPropertyChanging();
					this._TaxId = value;
					this.SendPropertyChanged("TaxId");
					this.OnTaxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultBoard", DbType="NVarChar(64)")]
		public string DefaultBoard
		{
			get
			{
				return this._DefaultBoard;
			}
			set
			{
				if ((this._DefaultBoard != value))
				{
					this.OnDefaultBoardChanging(value);
					this.SendPropertyChanging();
					this._DefaultBoard = value;
					this.SendPropertyChanged("DefaultBoard");
					this.OnDefaultBoardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessKey", DbType="NVarChar(25)")]
		public string AccessKey
		{
			get
			{
				return this._AccessKey;
			}
			set
			{
				if ((this._AccessKey != value))
				{
					this.OnAccessKeyChanging(value);
					this.SendPropertyChanging();
					this._AccessKey = value;
					this.SendPropertyChanged("AccessKey");
					this.OnAccessKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactive", DbType="Int NOT NULL")]
		public int Inactive
		{
			get
			{
				return this._Inactive;
			}
			set
			{
				if ((this._Inactive != value))
				{
					this.OnInactiveChanging(value);
					this.SendPropertyChanging();
					this._Inactive = value;
					this.SendPropertyChanged("Inactive");
					this.OnInactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(255)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityDistance", DbType="Int")]
		public System.Nullable<int> CityDistance
		{
			get
			{
				return this._CityDistance;
			}
			set
			{
				if ((this._CityDistance != value))
				{
					this.OnCityDistanceChanging(value);
					this.SendPropertyChanging();
					this._CityDistance = value;
					this.SendPropertyChanged("CityDistance");
					this.OnCityDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosTerminalID", DbType="NVarChar(50)")]
		public string VPosTerminalID
		{
			get
			{
				return this._VPosTerminalID;
			}
			set
			{
				if ((this._VPosTerminalID != value))
				{
					this.OnVPosTerminalIDChanging(value);
					this.SendPropertyChanging();
					this._VPosTerminalID = value;
					this.SendPropertyChanged("VPosTerminalID");
					this.OnVPosTerminalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosMerchantID", DbType="NVarChar(50)")]
		public string VPosMerchantID
		{
			get
			{
				return this._VPosMerchantID;
			}
			set
			{
				if ((this._VPosMerchantID != value))
				{
					this.OnVPosMerchantIDChanging(value);
					this.SendPropertyChanging();
					this._VPosMerchantID = value;
					this.SendPropertyChanged("VPosMerchantID");
					this.OnVPosMerchantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosProvUserID", DbType="NVarChar(50)")]
		public string VPosProvUserID
		{
			get
			{
				return this._VPosProvUserID;
			}
			set
			{
				if ((this._VPosProvUserID != value))
				{
					this.OnVPosProvUserIDChanging(value);
					this.SendPropertyChanging();
					this._VPosProvUserID = value;
					this.SendPropertyChanged("VPosProvUserID");
					this.OnVPosProvUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosUserID", DbType="NVarChar(50)")]
		public string VPosUserID
		{
			get
			{
				return this._VPosUserID;
			}
			set
			{
				if ((this._VPosUserID != value))
				{
					this.OnVPosUserIDChanging(value);
					this.SendPropertyChanging();
					this._VPosUserID = value;
					this.SendPropertyChanged("VPosUserID");
					this.OnVPosUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosProvisionPassword", DbType="NVarChar(50)")]
		public string VPosProvisionPassword
		{
			get
			{
				return this._VPosProvisionPassword;
			}
			set
			{
				if ((this._VPosProvisionPassword != value))
				{
					this.OnVPosProvisionPasswordChanging(value);
					this.SendPropertyChanging();
					this._VPosProvisionPassword = value;
					this.SendPropertyChanged("VPosProvisionPassword");
					this.OnVPosProvisionPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPosCompanyName", DbType="NVarChar(1024)")]
		public string VPosCompanyName
		{
			get
			{
				return this._VPosCompanyName;
			}
			set
			{
				if ((this._VPosCompanyName != value))
				{
					this.OnVPosCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._VPosCompanyName = value;
					this.SendPropertyChanged("VPosCompanyName");
					this.OnVPosCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Background", DbType="NVarChar(50)")]
		public string Background
		{
			get
			{
				return this._Background;
			}
			set
			{
				if ((this._Background != value))
				{
					this.OnBackgroundChanging(value);
					this.SendPropertyChanging();
					this._Background = value;
					this.SendPropertyChanged("Background");
					this.OnBackgroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreground", DbType="NVarChar(50)")]
		public string Foreground
		{
			get
			{
				return this._Foreground;
			}
			set
			{
				if ((this._Foreground != value))
				{
					this.OnForegroundChanging(value);
					this.SendPropertyChanging();
					this._Foreground = value;
					this.SendPropertyChanged("Foreground");
					this.OnForegroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreground2", DbType="NVarChar(50)")]
		public string Foreground2
		{
			get
			{
				return this._Foreground2;
			}
			set
			{
				if ((this._Foreground2 != value))
				{
					this.OnForeground2Changing(value);
					this.SendPropertyChanging();
					this._Foreground2 = value;
					this.SendPropertyChanged("Foreground2");
					this.OnForeground2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Background2", DbType="NVarChar(50)")]
		public string Background2
		{
			get
			{
				return this._Background2;
			}
			set
			{
				if ((this._Background2 != value))
				{
					this.OnBackground2Changing(value);
					this.SendPropertyChanging();
					this._Background2 = value;
					this.SendPropertyChanged("Background2");
					this.OnBackground2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="VarChar(50)")]
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="VarChar(50)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWinter", DbType="Int")]
		public System.Nullable<int> IsWinter
		{
			get
			{
				return this._IsWinter;
			}
			set
			{
				if ((this._IsWinter != value))
				{
					this.OnIsWinterChanging(value);
					this.SendPropertyChanging();
					this._IsWinter = value;
					this.SendPropertyChanged("IsWinter");
					this.OnIsWinterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePage", DbType="Int")]
		public System.Nullable<int> HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this.OnHomePageChanging(value);
					this.SendPropertyChanging();
					this._HomePage = value;
					this.SendPropertyChanged("HomePage");
					this.OnHomePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingComId", DbType="NVarChar(400)")]
		public string BookingComId
		{
			get
			{
				return this._BookingComId;
			}
			set
			{
				if ((this._BookingComId != value))
				{
					this.OnBookingComIdChanging(value);
					this.SendPropertyChanging();
					this._BookingComId = value;
					this.SendPropertyChanged("BookingComId");
					this.OnBookingComIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_RACKVIEW]")]
	public partial class _RACKVIEW
	{
		
		private int _Id;
		
		private int _HotelId;
		
		private string _RoomNo;
		
		private string _RoomGroup;
		
		private int _RoomTypeId;
		
		private int _IsRoomOrBed;
		
		private int _IsReady;
		
		private int _RoomStatusId;
		
		private int _TheOrder;
		
		private int _IsInCapacity;
		
		private string _LeftRoom;
		
		private string _RightRoom;
		
		private string _FrontRoom;
		
		private string _BackRoom;
		
		private string _Description;
		
		private int _Capacity;
		
		private int _MinPax;
		
		private int _MaxPax;
		
		private int _Floor;
		
		private string _Color;
		
		private System.Nullable<int> _HKStationId;
		
		private string _Block;
		
		private System.Nullable<System.DateTime> _Created_Date;
		
		private int _RoomId;
		
		private string _RoomColor;
		
		private string _RoomStatusName;
		
		private int _RoomStatus;
		
		private int _RoomCanSold;
		
		private string _RoomTypeName;
		
		private int _HKStayOver;
		
		private int _HKCheckout;
		
		private int _HKFree;
		
		private int _HKVIPStayOver;
		
		private int _HKVIPCheckinAdd;
		
		private System.DateTime _OdeonDate;
		
		private int _IsFeatured;
		
		private int _ArrId;
		
		private string _ArrName;
		
		private int _DepId;
		
		private string _DepName;
		
		private int _ProblemId;
		
		private int _ProblemIsClose;
		
		private int _InId;
		
		private string _InVIPStatusText;
		
		private string _InVIPStatusColor;
		
		private string _InName;
		
		private System.DateTime _InFromdate;
		
		private System.DateTime _InTodate;
		
		private System.TimeSpan _InFromtime;
		
		private System.TimeSpan _InTotime;
		
		private int _InAdult;
		
		private int _InNumberOfChild;
		
		private int _InNumberOfBaby;
		
		private string _InAgency;
		
		private string _InGroup;
		
		private System.Nullable<decimal> _InhouseBalance;
		
		public _RACKVIEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelId", DbType="Int NOT NULL")]
		public int HotelId
		{
			get
			{
				return this._HotelId;
			}
			set
			{
				if ((this._HotelId != value))
				{
					this._HotelId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomGroup", DbType="NVarChar(25)")]
		public string RoomGroup
		{
			get
			{
				return this._RoomGroup;
			}
			set
			{
				if ((this._RoomGroup != value))
				{
					this._RoomGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomTypeId", DbType="Int NOT NULL")]
		public int RoomTypeId
		{
			get
			{
				return this._RoomTypeId;
			}
			set
			{
				if ((this._RoomTypeId != value))
				{
					this._RoomTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRoomOrBed", DbType="Int NOT NULL")]
		public int IsRoomOrBed
		{
			get
			{
				return this._IsRoomOrBed;
			}
			set
			{
				if ((this._IsRoomOrBed != value))
				{
					this._IsRoomOrBed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReady", DbType="Int NOT NULL")]
		public int IsReady
		{
			get
			{
				return this._IsReady;
			}
			set
			{
				if ((this._IsReady != value))
				{
					this._IsReady = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomStatusId", DbType="Int NOT NULL")]
		public int RoomStatusId
		{
			get
			{
				return this._RoomStatusId;
			}
			set
			{
				if ((this._RoomStatusId != value))
				{
					this._RoomStatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheOrder", DbType="Int NOT NULL")]
		public int TheOrder
		{
			get
			{
				return this._TheOrder;
			}
			set
			{
				if ((this._TheOrder != value))
				{
					this._TheOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInCapacity", DbType="Int NOT NULL")]
		public int IsInCapacity
		{
			get
			{
				return this._IsInCapacity;
			}
			set
			{
				if ((this._IsInCapacity != value))
				{
					this._IsInCapacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftRoom", DbType="NVarChar(25)")]
		public string LeftRoom
		{
			get
			{
				return this._LeftRoom;
			}
			set
			{
				if ((this._LeftRoom != value))
				{
					this._LeftRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightRoom", DbType="NVarChar(25)")]
		public string RightRoom
		{
			get
			{
				return this._RightRoom;
			}
			set
			{
				if ((this._RightRoom != value))
				{
					this._RightRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrontRoom", DbType="NVarChar(25)")]
		public string FrontRoom
		{
			get
			{
				return this._FrontRoom;
			}
			set
			{
				if ((this._FrontRoom != value))
				{
					this._FrontRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackRoom", DbType="NVarChar(25)")]
		public string BackRoom
		{
			get
			{
				return this._BackRoom;
			}
			set
			{
				if ((this._BackRoom != value))
				{
					this._BackRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this._Capacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinPax", DbType="Int NOT NULL")]
		public int MinPax
		{
			get
			{
				return this._MinPax;
			}
			set
			{
				if ((this._MinPax != value))
				{
					this._MinPax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPax", DbType="Int NOT NULL")]
		public int MaxPax
		{
			get
			{
				return this._MaxPax;
			}
			set
			{
				if ((this._MaxPax != value))
				{
					this._MaxPax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int NOT NULL")]
		public int Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this._Floor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKStationId", DbType="Int")]
		public System.Nullable<int> HKStationId
		{
			get
			{
				return this._HKStationId;
			}
			set
			{
				if ((this._HKStationId != value))
				{
					this._HKStationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Block", DbType="NVarChar(25)")]
		public string Block
		{
			get
			{
				return this._Block;
			}
			set
			{
				if ((this._Block != value))
				{
					this._Block = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this._Created_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomId", DbType="Int NOT NULL")]
		public int RoomId
		{
			get
			{
				return this._RoomId;
			}
			set
			{
				if ((this._RoomId != value))
				{
					this._RoomId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomColor", DbType="NVarChar(50)")]
		public string RoomColor
		{
			get
			{
				return this._RoomColor;
			}
			set
			{
				if ((this._RoomColor != value))
				{
					this._RoomColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomStatusName", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string RoomStatusName
		{
			get
			{
				return this._RoomStatusName;
			}
			set
			{
				if ((this._RoomStatusName != value))
				{
					this._RoomStatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomStatus", DbType="Int NOT NULL")]
		public int RoomStatus
		{
			get
			{
				return this._RoomStatus;
			}
			set
			{
				if ((this._RoomStatus != value))
				{
					this._RoomStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomCanSold", DbType="Int NOT NULL")]
		public int RoomCanSold
		{
			get
			{
				return this._RoomCanSold;
			}
			set
			{
				if ((this._RoomCanSold != value))
				{
					this._RoomCanSold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomTypeName", DbType="NVarChar(50)")]
		public string RoomTypeName
		{
			get
			{
				return this._RoomTypeName;
			}
			set
			{
				if ((this._RoomTypeName != value))
				{
					this._RoomTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKStayOver", DbType="Int NOT NULL")]
		public int HKStayOver
		{
			get
			{
				return this._HKStayOver;
			}
			set
			{
				if ((this._HKStayOver != value))
				{
					this._HKStayOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKCheckout", DbType="Int NOT NULL")]
		public int HKCheckout
		{
			get
			{
				return this._HKCheckout;
			}
			set
			{
				if ((this._HKCheckout != value))
				{
					this._HKCheckout = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKFree", DbType="Int NOT NULL")]
		public int HKFree
		{
			get
			{
				return this._HKFree;
			}
			set
			{
				if ((this._HKFree != value))
				{
					this._HKFree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKVIPStayOver", DbType="Int NOT NULL")]
		public int HKVIPStayOver
		{
			get
			{
				return this._HKVIPStayOver;
			}
			set
			{
				if ((this._HKVIPStayOver != value))
				{
					this._HKVIPStayOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HKVIPCheckinAdd", DbType="Int NOT NULL")]
		public int HKVIPCheckinAdd
		{
			get
			{
				return this._HKVIPCheckinAdd;
			}
			set
			{
				if ((this._HKVIPCheckinAdd != value))
				{
					this._HKVIPCheckinAdd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdeonDate", DbType="Date NOT NULL")]
		public System.DateTime OdeonDate
		{
			get
			{
				return this._OdeonDate;
			}
			set
			{
				if ((this._OdeonDate != value))
				{
					this._OdeonDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFeatured", DbType="Int NOT NULL")]
		public int IsFeatured
		{
			get
			{
				return this._IsFeatured;
			}
			set
			{
				if ((this._IsFeatured != value))
				{
					this._IsFeatured = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArrId", DbType="Int NOT NULL")]
		public int ArrId
		{
			get
			{
				return this._ArrId;
			}
			set
			{
				if ((this._ArrId != value))
				{
					this._ArrId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArrName", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string ArrName
		{
			get
			{
				return this._ArrName;
			}
			set
			{
				if ((this._ArrName != value))
				{
					this._ArrName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepId", DbType="Int NOT NULL")]
		public int DepId
		{
			get
			{
				return this._DepId;
			}
			set
			{
				if ((this._DepId != value))
				{
					this._DepId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this._DepName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProblemId", DbType="Int NOT NULL")]
		public int ProblemId
		{
			get
			{
				return this._ProblemId;
			}
			set
			{
				if ((this._ProblemId != value))
				{
					this._ProblemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProblemIsClose", DbType="Int NOT NULL")]
		public int ProblemIsClose
		{
			get
			{
				return this._ProblemIsClose;
			}
			set
			{
				if ((this._ProblemIsClose != value))
				{
					this._ProblemIsClose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InId", DbType="Int NOT NULL")]
		public int InId
		{
			get
			{
				return this._InId;
			}
			set
			{
				if ((this._InId != value))
				{
					this._InId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InVIPStatusText", DbType="NVarChar(50)")]
		public string InVIPStatusText
		{
			get
			{
				return this._InVIPStatusText;
			}
			set
			{
				if ((this._InVIPStatusText != value))
				{
					this._InVIPStatusText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InVIPStatusColor", DbType="NVarChar(50)")]
		public string InVIPStatusColor
		{
			get
			{
				return this._InVIPStatusColor;
			}
			set
			{
				if ((this._InVIPStatusColor != value))
				{
					this._InVIPStatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InName", DbType="NVarChar(101)")]
		public string InName
		{
			get
			{
				return this._InName;
			}
			set
			{
				if ((this._InName != value))
				{
					this._InName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InFromdate", DbType="Date NOT NULL")]
		public System.DateTime InFromdate
		{
			get
			{
				return this._InFromdate;
			}
			set
			{
				if ((this._InFromdate != value))
				{
					this._InFromdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InTodate", DbType="Date NOT NULL")]
		public System.DateTime InTodate
		{
			get
			{
				return this._InTodate;
			}
			set
			{
				if ((this._InTodate != value))
				{
					this._InTodate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InFromtime", DbType="Time NOT NULL")]
		public System.TimeSpan InFromtime
		{
			get
			{
				return this._InFromtime;
			}
			set
			{
				if ((this._InFromtime != value))
				{
					this._InFromtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InTotime", DbType="Time NOT NULL")]
		public System.TimeSpan InTotime
		{
			get
			{
				return this._InTotime;
			}
			set
			{
				if ((this._InTotime != value))
				{
					this._InTotime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InAdult", DbType="Int NOT NULL")]
		public int InAdult
		{
			get
			{
				return this._InAdult;
			}
			set
			{
				if ((this._InAdult != value))
				{
					this._InAdult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InNumberOfChild", DbType="Int NOT NULL")]
		public int InNumberOfChild
		{
			get
			{
				return this._InNumberOfChild;
			}
			set
			{
				if ((this._InNumberOfChild != value))
				{
					this._InNumberOfChild = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InNumberOfBaby", DbType="Int NOT NULL")]
		public int InNumberOfBaby
		{
			get
			{
				return this._InNumberOfBaby;
			}
			set
			{
				if ((this._InNumberOfBaby != value))
				{
					this._InNumberOfBaby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InAgency", DbType="NVarChar(125)")]
		public string InAgency
		{
			get
			{
				return this._InAgency;
			}
			set
			{
				if ((this._InAgency != value))
				{
					this._InAgency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InGroup", DbType="NVarChar(150)")]
		public string InGroup
		{
			get
			{
				return this._InGroup;
			}
			set
			{
				if ((this._InGroup != value))
				{
					this._InGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InhouseBalance", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> InhouseBalance
		{
			get
			{
				return this._InhouseBalance;
			}
			set
			{
				if ((this._InhouseBalance != value))
				{
					this._InhouseBalance = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
