<?xml version="1.0" encoding="utf-8"?><Database Name="OdeonAir" Class="dbLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=myodeon.com;Initial Catalog=OdeonAir;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CESTURConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hotel" Member="Hotel">
    <Type Name="Hotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsMainSourceHotel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShortDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HotelType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoomNumberDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Bolge" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Ilce" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Mevki" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="AddressSame" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddressInvoice" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="AddressInvoiceCity" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="AddressInvoiceCountry" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CommercialName" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Phone3" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Airport" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AirportDistance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="Web" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Gm" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TaxOffice" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TaxId" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DefaultBoard" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="AccessKey" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CityDistance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VPosTerminalID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VPosMerchantID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VPosProvUserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VPosUserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VPosProvisionPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VPosCompanyName" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Background" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Foreground" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Foreground2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Background2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsWinter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomePage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookingComId" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[_RACKVIEW]" Member="_RACKVIEW">
    <Type Name="_RACKVIEW">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNo" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="RoomGroup" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="RoomTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRoomOrBed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsReady" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TheOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsInCapacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LeftRoom" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="RightRoom" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FrontRoom" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="BackRoom" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinPax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxPax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Floor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HKStationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Block" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoomStatusName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RoomStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomCanSold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HKStayOver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKCheckout" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKFree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKVIPStayOver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKVIPCheckinAdd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OdeonDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsFeatured" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArrId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArrName" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="DepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepName" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProblemIsClose" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InVIPStatusText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InVIPStatusColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InName" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="InFromdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="InTodate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="InFromtime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="InTotime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="InAdult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InNumberOfChild" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InNumberOfBaby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InAgency" Type="System.String" DbType="NVarChar(125)" CanBeNull="true" />
      <Column Name="InGroup" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="InhouseBalance" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationVIEW" Member="ReservationVIEW">
    <Type Name="ReservationVIEW">
      <Column Name="RoomNo" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VIPStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VIPStatusText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VIPStatusColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ReservationRemark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AgencyName" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="StatusText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BoardName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoomType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReservationTypeText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fromdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Todate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="OriginalTodate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Fromtime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Totime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Leavetime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="BoardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomTypeIdForPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OriginalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChannelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservationTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsCityLedger" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultFolioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MasterFolioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccomTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfChild" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfBaby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BabyAge1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BabyAge2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Extra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Extra2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialCode2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Walkin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Forecast" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomFeatures" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LateCheckout" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllotmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SafeKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LockUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UndoCancelDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NightMove" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShareId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShareMaster" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NatMarketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Voucher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExternalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SaveState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SaveStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FixedPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoPos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OptionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BedSheet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MasterRefresh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaxInfo" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Stay" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservation">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fromdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Todate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="OriginalTodate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Fromtime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Totime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Leavetime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="BoardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomTypeIdForPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OriginalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChannelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservationTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsCityLedger" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultFolioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MasterFolioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccomTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfChild" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildAge4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfBaby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BabyAge1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BabyAge2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Extra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Extra2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialCode2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Walkin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Forecast" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomFeatures" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LateCheckout" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllotmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SafeKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LockUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UndoCancelDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NightMove" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShareId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShareMaster" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NatMarketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Voucher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExternalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SaveState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SaveStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FixedPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoPos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OptionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BedSheet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MasterRefresh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RoomType" Member="RoomType">
    <Type Name="RoomType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberInHotel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameEng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DescriptionEng" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FrontOfficeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MinPax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxPax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFeatured" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKStayOver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKCheckout" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKFree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKVIPStayOver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HKVIPCheckinAdd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>